version: '3.4'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: ecabs-zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    container_name: ecabs-kafka
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://ecabs-kafka:9093,OUTSIDE://172.31.0.51:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: ecabs-zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    depends_on:
      - zookeeper
    volumes:
      - ./:/etc/kafka

  ecabs-booking-producer:
    image: ecabs-booking-producer:latest
    build:
      context: ./ecabs-booking-producer
      dockerfile: Dockerfile
    container_name: ecabs-booking-producer
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    volumes:
      - app-logs:/logs
    links:
      - kafka:kafka

  ecabs-booking-consumer:
    image: ecabs-booking-consumer:latest
    build:
      context: ./ecabs-booking-consumer
      dockerfile: Dockerfile
    container_name: ecabs-booking-consumer
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - kafka
      - mongo
    volumes:
      - app-logs:/logs
    links:
      - kafka:kafka
      - mongo:mongo

  mongo:
    image: mongo:latest
    container_name: ecabs-mongo
    restart: always
    volumes:
      - ./data/mongodb/db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo ecabs-mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  app-logs: